site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono


    - name: Deploy MkDocs
  uses: mhausenblas/mkdocs-deploy-gh-pages@1.24
