site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
<<<<<<< Updated upstream
    primary: amber
    accent: indigo
=======
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono
>>>>>>> Stashed changes
