site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top


plugins:
  - search




copyright: Copyright &copy; 2022 Leonardo Vieira


extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/MrNokdef
      name: Leo's Personal Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:<leonardo.v.alvarez@hotmail.com>
      name: Shoot me an E-Mail
    - icon: material-youtube
      link: https://www.youtube.com/nokdef
      name: Nokdef's Channel