site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top


plugins:
  - search


extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/MrNokdef
    - icon: fontawesome-brands-youtube
      link: https://www.youtube.com/nokdef
    - icon: fontawesome-brands-unity
      link: https://assetstore.unity.com/publishers/48767
    - icon: fontawesome-brands-artstation
      link: https://www.artstation.com/nokdef

copyright: Copyright &copy; 2022 Leonardo Vieira Test2


