site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono

features:
  - navigation.tabs
  - navigation.indexes
  - navigation.top


plugins:
 - search
extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/MrNokdef
      name: Leo's Personal Twitter
    - icon: fontawesome/solid/paper-plane
      link: mailto:<leonardo.v.alvarez@hotmail.com>
    - icon: fontawesome-brands-youtube
      link: https://www.youtube.com/nokdef
      name: Nokdef's Channel
    - icon: fontawesome-brands-youtube
      link: https://www.youtube.com/pilotostudio
      name: Piloto Studio's Channel
    - icon: fontawesome-brands-unity
      link: https://assetstore.unity.com/publishers/48767
      name: Our Online Store
    - icon: fontawesome-brands-artstation
      link: https://www.artstation.com/nokdef

copyright: Copyright &copy; 2022 Leonardo Vieira Test1


