site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top


plugins:
  - search


copyright: Copyright &copy; 2022 Leonardo Vieira Test1


