site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
  icon:
    repo: fontawesome/brands/twitter
  custom_dir: overrides

plugins:
  - search




copyright: Copyright &copy; 2022 Leonardo Vieira


extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/MrNokdef
      name: Leo's Personal Twitter
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/nokdef
      name: Nokdef's Channel
    - icon: fontawesome/brands/unity
      link: https://assetstore.unity.com/publishers/48767
      name: Our Online Store
    - icon: fontawesome/brands/artstation
      link: https://www.artstation.com/nokdef
    - icon: fontawesome/solid/paper-plane
      link: mailto:<leonardo.v.alvarez@hotmail.com>
      name: Shoot me an E-Mail
  generator: false


repo_url: https://twitter.com/MrNokdef
repo_name: Follow me on Twitter!

markdown_extensions:
  - meta