site_name: Nokdef
theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue
  font:
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top


plugins:
  - search




copyright: Copyright &copy; 2022 Leonardo Vieira Test2


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://twitter.com/MrNokdef
    - icon: fontawesome/brands/gitter
      link: https://twitter.com/MrNokdef
    - icon: fontawesome/brands/docker
      link: https://twitter.com/MrNokdef
    - icon: fontawesome/brands/python
      link: https://twitter.com/MrNokdef
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MrNokdef